### ISSUE TITLE
Do not disturb turns OFF after resume from sleep

### ISSUE THREAD

**Issue by v-marinkov** [kylecorry31/gnome-shell-extension-do-not-disturb#33] opened 2019-01-25 14:27 UTC
**Distribution (run `cat /etc/os-release`):**
I am on Pop_OS! 18.10

 NAME="Ubuntu"
VERSION="18.10 (Cosmic Cuttlefish)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.10"
VERSION_ID="18.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic
 
 
**Do not disturb settings (run `gsettings --schemadir ~/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/schemas list-recursively org.gnome.shell.extensions.kylecorry31-do-not-disturb`):**
GLib-GIO-Message: 15:24:02.065: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
org.gnome.shell.extensions.kylecorry31-do-not-disturb do-not-disturb false
org.gnome.shell.extensions.kylecorry31-do-not-disturb mute-sounds false
org.gnome.shell.extensions.kylecorry31-do-not-disturb show-count true
org.gnome.shell.extensions.kylecorry31-do-not-disturb show-dot false
org.gnome.shell.extensions.kylecorry31-do-not-disturb show-icon true

**Log output (`journalctl -b | grep donotdisturb@kylecorry31`)**

**Issue/Bug Description:**
"Do not disturb" turns itself off after resume from sleep

**Steps to reproduce (if you know):**
Turn "Do not disturb" ON. Put computer to sleep. Wake it up -> "Do not disturb" is OFF

**Expected behavior:**
Stay ON until manually switched off since opening the notification panel to turn it ON is distracting enough with all the suppressed old notifications.

**Comment by kylecorry31** [comment] 2019-01-25 18:58
I have confirmed this, I'll push out a fix within the next couple of days.

**Comment by v-marinkov** [comment] 2019-02-06 09:36
Hi, do you know when the updated version will be available at gnome.org? Thanks!

**Comment by kylecorry31** [comment] 2019-02-06 10:37
Hi, I submitted the update to gnome.org 10 days ago, and in order for it to be available there, it needs to be reviewed. The people at gnome.org typically take a week or two to do that, so it should be out soon (I don't have any control over that unfortunately).

**Comment by v-marinkov** [comment] 2019-02-07 10:09
I thought so. Thanks for the work!

**Comment by v-marinkov** [comment] 2019-04-02 15:11
Hi, the extension finally got updated on Gnome's website, but the problem persists. How can I check if it is the correct version?
Thanks

**Comment by kylecorry31** [comment] 2019-04-02 15:35
Yeah, that took a lot longer than expected. Make sure there are no updates for the extension on this page: https://extensions.gnome.org/local/ 

I assume you are on the latest version though - I can't seem to replicate this, can you describe how you are putting the computer to sleep so I can make sure I am doing it the same way you are?

You may want to restart the GNOME shell just in case the new extension was not completely loaded (Alt-F2 -> R -> Enter)

**Comment by kylecorry31** [comment] 2019-04-02 15:48
Also, when you say that do not disturb mode turns off after sleep, do you have to turn it back on manually when it wakes back up or does it just let a few notifications in and re-enable itself?

**Comment by v-marinkov** [comment] 2019-04-02 19:03
I figured it out. The mute mode persists over a sleep/wake cycle. But when the screen is turned off without putting the computer to sleep (in Pop_OS the setting is called "Blank screen") the entire gnome shell kind of restarts (windows popping and virtual workspace often changed to 1) and then the Do Not Disturb is turned off.

**Comment by kylecorry31** [comment] 2019-04-03 10:17
Ok, I am able to replicate this - I will have to do a bit of research to see why this happens, and then I'll get back to you. Thank you for the details!

**Comment by kylecorry31** [comment] 2019-04-03 10:43
So the problem is that when the GNOME shell is closing with the blank screen setting, it changes the GNOME Presence value (monitored by the DND extension and used to actually enable DND), so the extension believes it is a valid action to disable DND...

I will consult with the people at System76 to see the preferred action here and get back to you.

**Comment by kylecorry31** [comment] 2019-04-03 19:08
The consensus was that I will be removing the monitor for the Presence value, which will fix this issue.

**Comment by kylecorry31** [comment] 2019-04-03 19:14
I just published the changes to GNOME extensions, hopefully, it publishes faster than before.

**Closed as completed by kylecorry31** 2019-04-03 19:14 UTC
Labels: bug, confirmed, fix-committed

**Comment by v-marinkov** [comment] 2019-04-03 20:03
Thank you!
