### ISSUE TITLE
Ubuntu 18.04 do not disturb icon not appear when extension is active

### ISSUE THREAD

**Issue by caseca** [kylecorry31/gnome-shell-extension-do-not-disturb#17] opened 2018-10-15 18:23 UTC
![outro_erro](https://user-images.githubusercontent.com/4641681/46969990-2afda700-d08e-11e8-89c7-745b4a7b4e0c.png)

**Comment by kylecorry31** [comment] 2018-10-15 18:40
Hello,

Can you open GNOME Tweaks Tool and go to the Extensions screen, then click the settings button next to the Do Not Disturb extension and verify that the "Show Icon" setting is checked?

**Comment by caseca** [comment] 2018-10-15 19:00
![outro_erro3](https://user-images.githubusercontent.com/4641681/46971793-5a62e280-d093-11e8-8243-f1b17973c4c9.png)

**Comment by kylecorry31** [comment] 2018-10-15 19:22
Thank you, I will look into this!

**Comment by kylecorry31** [comment] 2018-10-15 19:43
The issue is that Ubuntu GNOME does not ship with the notification disabled icon, so I need to provide a fallback if that is the case. I will look into packaging the extension with the icon it needs, or use a different system icon if that notification one is not available.

**Comment by kylecorry31** [comment] 2018-10-15 20:27
Fixed in commit 911545b818ef81abe11febc5cba0b4f747910c4e.

**Closed as completed by kylecorry31** 2018-10-15 20:27 UTC
Labels: bug
